name: Create GitHub Release with Short Changelog

on:
  push:
    tags:
      - 'v*'
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for repo scripts if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps for AI generator
        run: |
          npm ci --omit=dev || npm i --omit=dev

      - name: Generate AI release notes (with fallback)
        id: gen_notes
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: https://openrouter.ai/api/v1
          OPENROUTER_MODEL: openai/gpt-4o-mini
        run: |
          node ./scripts/generate-ai-release-notes.js "${{ github.ref_name }}" || pwsh ./scripts/release-notes.ps1 "${{ github.ref_name }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


